version: '3.8'

networks:
  internal_network:
    internal: true
  tunnel:
    external: true

services:
  nuxt-3-stater-web-app-service:
    image: nuxt-3-stater-web-app:1.0
    container_name: nuxt-3-stater-web-app
    ports:
      - 3000:3000
    restart: always
    networks:
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.couchdb_master.loadbalancer.server.port=3000"
      - "traefik.http.routers.couchdb_master.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.couchdb_master.entrypoints=web"
      - "traefik.docker.network=internal_network"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  traefik_proxy:
    container_name: traefik_proxy
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - internal_network
      - tunnel
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
