version: '3.8'

services:
  app:
    platform: linux/arm64
    image: nuxt-3-stater-web-app:1.0
    container_name: nuxt-3-stater-web-app
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: /app/entrypoint.sh
    environment:
      NODE_ENV: development
